package eu.kdvelectronics.upyandroid.ui

import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.size
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.IconButton
import androidx.compose.material3.LocalTextStyle
import androidx.compose.material3.PlainTooltip
import androidx.compose.material3.Text
import androidx.compose.material3.TooltipAnchorPosition
import androidx.compose.material3.TooltipBox
import androidx.compose.material3.TooltipDefaults
import androidx.compose.material3.rememberTooltipState
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalDensity
import androidx.compose.ui.semantics.clearAndSetSemantics
import androidx.compose.ui.semantics.contentDescription
import androidx.compose.ui.semantics.semantics
import androidx.compose.ui.text.PlatformTextStyle
import androidx.compose.ui.text.font.Font
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.style.LineHeightStyle
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import eu.kdvelectronics.upyandroid.R

// Every codepoint this app's own subsetted icon font
// (res/font/upy_symbols.ttf, regenerated by tools/generate-icon-font.sh
// -- see that script and ~/Downloads/new_icons.html, the confirmed icon
// sheet Part 10 of the plan is built from) actually holds. Kept as a
// single flat object, not grouped by screen, matching the font
// generation script's own ICON_NAMES list -- one name, one codepoint,
// one place to look either up.
object SymbolIcon {
    const val TERMINAL = 0xeb8e
    const val FOLDER = 0xe2c7
    const val CAMERA = 0xe3af
    const val SETTINGS = 0xe8b8
    const val LINK = 0xe250
    const val LINK_OFF = 0xe16f
    const val STOP = 0xe047
    const val PLAY_ARROW = 0xe037
    const val RESTART_ALT = 0xf053
    const val DELETE_SWEEP = 0xe16c
    const val KEYBOARD_ARROW_UP = 0xe316
    const val KEYBOARD_ARROW_DOWN = 0xe313
    const val DRIVE_FOLDER_UPLOAD = 0xe9a3
    const val NOTE_ADD = 0xe89c
    const val CREATE_NEW_FOLDER = 0xe2cc
    const val REFRESH = 0xe5d5
    const val ARROW_BACK = 0xe5c4
    const val MEMORY = 0xe322
    const val TERMINAL_2 = 0xfff8e
    const val PASSWORD_2 = 0xf4a9
    const val PUBLIC = 0xe80b
    const val LOCK = 0xe899
    const val SHOP = 0xe8c9
    const val ADB = 0xe60e
}

private val symbolFontFamily = FontFamily(Font(R.font.upy_symbols))

// One glyph from this app's own subsetted icon font, rendered as a
// fixed-dp-size square regardless of the system font-scale
// accessibility setting -- icon glyphs, unlike real text, should not
// grow when a user increases their text size (matching how a vector
// icon asset would behave). Achieved by dividing the target dp size by
// LocalDensity's own fontScale before expressing it as an sp fontSize
// (Compose's dp->sp conversion otherwise bakes fontScale back in).
//
// contentDescription is REQUIRED reasoning, not optional: without it,
// TalkBack reads out the raw private-use-area character itself, not
// anything meaningful. Pass null only when this glyph is purely
// decorative AND immediately adjacent to its own real text label
// (e.g. a Settings row that already has a full-sentence label next to
// its leading icon) -- clearAndSetSemantics{} then removes it from the
// accessibility tree entirely, rather than leaving a bare
// contentDescription = null (which Compose would otherwise still
// expose as an unlabeled node).
@Composable
fun Symbol(
    codepoint: Int,
    contentDescription: String?,
    modifier: Modifier = Modifier,
    tint: Color = Color.Unspecified,
    size: Dp = 24.dp,
) {
    val density = LocalDensity.current
    val fixedFontSize = (size.value / density.fontScale).sp
    val semanticsModifier = if (contentDescription != null) {
        Modifier.semantics { this.contentDescription = contentDescription }
    } else {
        Modifier.clearAndSetSemantics { }
    }
    Box(
        modifier = modifier.size(size).then(semanticsModifier),
        contentAlignment = Alignment.Center,
    ) {
        // Text (material3), not BasicText: resolves Color.Unspecified to
        // LocalContentColor.current automatically, same convention
        // androidx.compose.material3.Icon's own tint default uses.
        //
        // lineHeight/lineHeightStyle/includeFontPadding: without these,
        // Text inherits LocalTextStyle's own ABSOLUTE lineHeight (material3
        // bodyLarge's 24.sp), not one derived from fixedFontSize -- at
        // any system font scale other than 1.0 (real device state found
        // debugging this: 1.1), that 24.sp line box ends up taller than
        // this glyph's own actual rendered size, and Compose's default
        // (non-centered) distribution of that extra space is weighted
        // toward ascent -- pushing the glyph itself toward the bottom of
        // the still-Box-centered line box. Result: curved glyph bottoms
        // (circles, rounded corners) got their last 1-2px sheared off
        // while straight-edged glyphs (chevrons, squares) never showed
        // it. Pinning lineHeight to fixedFontSize + Center/None trim +
        // includeFontPadding=false makes the line box match the font's
        // own em-square exactly, so nothing overflows the Box and
        // nothing clips, at any font scale.
        Text(
            text = String(Character.toChars(codepoint)),
            fontFamily = symbolFontFamily,
            fontSize = fixedFontSize,
            lineHeight = fixedFontSize,
            style = LocalTextStyle.current.copy(
                lineHeightStyle = LineHeightStyle(
                    alignment = LineHeightStyle.Alignment.Center,
                    trim = LineHeightStyle.Trim.None,
                ),
                platformStyle = PlatformTextStyle(includeFontPadding = false),
            ),
            maxLines = 1,
            softWrap = false,
            color = tint,
        )
    }
}

// An icon-only IconButton's own contentDescription is invisible to a
// sighted user -- it only reaches TalkBack. This is the same label
// shown as a real Material3 tooltip on long-press (touch) or hover
// (mouse/stylus), so an icon-only action row (the terminal's history/
// interrupt/reset/clear row, e.g.) gets a visible text hint without
// needing a second, separately-maintained label string.
@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun TooltipIconButton(
    icon: Int,
    label: String,
    onClick: () -> Unit,
    modifier: Modifier = Modifier,
) {
    TooltipBox(
        positionProvider = TooltipDefaults.rememberTooltipPositionProvider(TooltipAnchorPosition.Above),
        tooltip = { PlainTooltip { Text(label) } },
        state = rememberTooltipState(),
        modifier = modifier,
    ) {
        IconButton(onClick = onClick) {
            Symbol(icon, contentDescription = label)
        }
    }
}
