#!/usr/bin/env bash
# Resyncs upy-android-docker/upy-android/ from a fresh `git archive` of
# the real upy-android repo, then re-applies the trims that make this a
# "genuine third-party dependencies are cloned, not vendored" snapshot
# (see tools/docker/Dockerfile's own header comment and
# tools/docker/openmv-manifest.tsv):
#
#  - app/src/main/cpp/micropython_embed/ removed entirely -- fully
#    regenerated by the Dockerfile's own build stage, nothing unique
#    lives only there.
#  - my-overrides/openmv/'s 68 files confirmed byte-identical to a real
#    OpenMV upstream path (per openmv-manifest.tsv) are removed -- the
#    Dockerfile clones openmv and copies them in. The 14 remaining files
#    have no fetchable upstream source and stay.
#  - my-overrides/ulab/ removed entirely -- confirmed a clean, 100%
#    byte-identical copy of ulab's own code/ directory, the Dockerfile
#    clones ulab and copies it in wholesale.
#
# NOTE: this repo's OWN native-bringup/ now splits these into
# vendor/{openmv,ulab}/ (gitignored, pristine) vs my-overrides/{openmv,
# ulab}/ (tracked, ours-only) -- see .gitignore. The strip paths above
# still target the SOURCE repo's own (flat, unsplit) layout, since that
# repo has not been touched here (see project memory: never edit/sync
# it). If it's ever restructured to match, update the paths above too.
#
# Usage: ./tools/sync-upy-android.sh [path-to-real-upy-android-repo]
# Defaults to ../repos/upy-android if not given.

set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

SRC_REPO="${1:-../repos/upy-android}"
if [ ! -d "$SRC_REPO/.git" ]; then
    echo "error: $SRC_REPO is not a git repo (pass the real upy-android checkout path)" >&2
    exit 1
fi

rm -rf upy-android
mkdir -p upy-android
git -C "$SRC_REPO" archive --format=tar HEAD | tar -x -C upy-android

rm -rf upy-android/app/src/main/cpp/micropython_embed

while IFS=$'\t' read -r src dest; do
    rm -f "upy-android/native-bringup/my-overrides/openmv/$dest"
done < tools/docker/openmv-manifest.tsv

rm -rf upy-android/native-bringup/my-overrides/ulab

echo "Synced upy-android/ from $SRC_REPO ($(git -C "$SRC_REPO" rev-parse --short HEAD))"
